// Pure-Go Elixir backend (Phase 13, Tier-3). Elixir is NOT brace-delimited: a module/
// function body runs from a `do` to the matching `end`. So, like the Ruby backend, this
// tracks block depth by `do`/`fn` openers and the `end` closer rather than `{`/`}` — but it
// mirrors the Ruby/Python line-scanner STRUCTURE (a stack of open blocks, spans extended as
// we descend, blocks closed as we ascend). It is a deliberately lightweight scanner over the
// standard library (bufio/regexp/strings) — NOT a full grammar.
//
// Shapes recognized:
//   - `defmodule Name do`               -> a module (KindType). Name may be dotted
//     (`MyApp.User`); we keep the trailing segment.
//   - `def name(...)` / `def name do`   -> a public function with the enclosing module as Recv
//   - `defp name(...)`                  -> a private function (same treatment)
//   - `defmacro` / `defmacrop`          -> a macro definition (treated as a function)
//   - one-line `def name(args), do: expr` (the inline `do:` keyword form — emits a single-
//     line symbol, opens no block)
//
// Block model: a trailing `do` (block form) opens a block that `end` closes; an inline `do:`
// (keyword form, with a colon) does NOT. `fn ... end` anonymous functions open/close blocks
// too. Every `do`/`fn` token adds depth; every `end` subtracts. Only `defmodule`/`def`/
// `defp`/`defmacro`/`defmacrop` emit a symbol; other `do`-bearing constructs (`if`/`case`/
// `cond`/`for`/`with`/`receive`/`try`/`quote`) are anonymous depth so we find a def's `end`.
//
// Honest scope (heuristic): this models the static `defmodule`/`def` skeleton. Heavy
// metaprogramming — functions GENERATED by macros (`use`, `defstruct`, `Ecto.Schema` fields,
// `def`s emitted from a `quote`) — is invisible here; that dynamic surface is the LSP seam's
// lens, not this static scanner's. Calls are counted as `name(...)` and `Module.func(...)`,
// keeping the trailing simple name. `#` line comments are stripped; sigils/heredocs (`"""`)
// are approximated.
package ast

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

var (
	// `defmodule Name do` — a module. Name may be a dotted alias path (`MyApp.User`).
	exModuleRe = regexp.MustCompile(`^\s*defmodule\s+([A-Za-z_][A-Za-z0-9_.]*)`)

	// `def` / `defp` / `defmacro` / `defmacrop` name. The name may be wrapped in `(` args or
	// followed by `,`/`do`/`when`/`\` (default) — we capture the identifier after the keyword.
	// Elixir function names may end in `?` or `!`.
	exDefRe = regexp.MustCompile(`^\s*defp?(?:macro)?p?\s+([A-Za-z_][A-Za-z0-9_]*[?!]?)`)

	// Call sites: `name(` or `Module.func(` — an identifier optionally dotted before "(".
	exCallRe = regexp.MustCompile(`([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*[?!]?)\s*\(`)

	exKeyword = map[string]bool{
		"if": true, "unless": true, "case": true, "cond": true, "for": true,
		"with": true, "fn": true, "do": true, "end": true, "else": true,
		"when": true, "and": true, "or": true, "not": true, "in": true,
		"def": true, "defp": true, "defmodule": true, "defmacro": true,
		"defmacrop": true, "try": true, "rescue": true, "catch": true,
		"after": true, "receive": true, "quote": true, "import": true,
		"alias": true, "require": true, "use": true,
	}
)

// elixirParser scans Elixir source line-by-line. It is stateless across calls.
type elixirParser struct{}

var _ languageParser = elixirParser{}

// exBlock tracks an open `defmodule`/`def`-family block (a NAMED block we record as a symbol)
// so we can nest (a def inside a module is a function on that module) and compute spans. We
// store the symbol's INDEX (not a pointer — append may reallocate; same rationale as pyBlock).
// openDepth is the block depth right after this header opened; it closes when depth returns to
// that level. isModule marks `defmodule` so nested defs read it as their Recv.
type exBlock struct {
	idx       int
	openDepth int
	isModule  bool
}

func (elixirParser) symbols(path string) ([]Symbol, error) {
	syms, _, err := elixirScan(path, false)
	return syms, err
}

func (elixirParser) references(path string) ([]Reference, error) {
	_, refs, err := elixirScan(path, true)
	return refs, err
}

func (elixirParser) calls(path string) (map[string][]string, error) {
	syms, refs, err := elixirScan(path, true)
	if err != nil {
		return nil, err
	}
	return groupBraceCalls(syms, refs), nil
}

// elixirScan is the shared single pass. It tracks net block depth over `do`/`fn` openers and
// `end` closers and maintains a stack of named (defmodule/def) blocks, closing them as `end`
// brings depth back to their open level. Spans of all open named blocks are extended to each
// line before close-out.
func elixirScan(path string, wantRefs bool) ([]Symbol, []Reference, error) {
	f, err := os.Open(path) //nolint:gosec // path is supplied by the worktree-confined walker
	if err != nil {
		return nil, nil, fmt.Errorf("open elixir file: %w", err)
	}
	defer f.Close() //nolint:errcheck // read-only handle

	var syms []Symbol
	var refs []Reference
	var stack []exBlock
	depth := 0

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)

	lineNo := 0
	for sc.Scan() {
		lineNo++
		raw := sc.Text()
		code := stripElixirComment(raw)
		if strings.TrimSpace(code) == "" {
			continue
		}

		depthBefore := depth

		// Extend every open named block's span to this line.
		for i := range stack {
			if lineNo > syms[stack[i].idx].Span.EndLine {
				syms[stack[i].idx].Span.EndLine = lineNo
			}
		}

		delta := elixirLineDelta(code)

		switch {
		case matchHeader(exModuleRe, code) != "":
			name := exLastSegment(matchHeader(exModuleRe, code))
			syms = append(syms, Symbol{Name: name, Kind: KindType, Span: Span{File: path, StartLine: lineNo, EndLine: lineNo}})
			if delta > 0 {
				stack = append(stack, exBlock{idx: len(syms) - 1, openDepth: depthBefore, isModule: true})
			}

		case matchHeader(exDefRe, code) != "":
			name := matchHeader(exDefRe, code)
			// Elixir functions are always KindFunc (there are no methods); when nested in a
			// module they carry that module as their Recv, matching how callers reference them
			// as `Module.func`.
			recv := nearestModule(syms, stack)
			syms = append(syms, Symbol{Name: name, Kind: KindFunc, Recv: recv, Span: Span{File: path, StartLine: lineNo, EndLine: lineNo}})
			// A block-form def (trailing `do`) opens a block; an inline `do:` def does not.
			if delta > 0 {
				stack = append(stack, exBlock{idx: len(syms) - 1, openDepth: depthBefore})
			}
			// Header argument / default calls after the def name's first `(`.
			if wantRefs {
				if op := strings.IndexByte(code, '('); op >= 0 {
					refs = append(refs, elixirScanCalls(code[op+1:], path, lineNo)...)
				}
			}

		default:
			if wantRefs {
				refs = append(refs, elixirScanCalls(code, path, lineNo)...)
			}
		}

		depth += delta
		// Close any named blocks whose matching `end` we have now reached.
		for len(stack) > 0 && depth <= stack[len(stack)-1].openDepth {
			stack = stack[:len(stack)-1]
		}
	}
	if err := sc.Err(); err != nil {
		return nil, nil, fmt.Errorf("scan elixir file: %w", err)
	}
	return syms, refs, nil
}

// elixirLineDelta returns the net block-depth change for one comment/string-stripped line.
// A `do`/`fn` token opens a block; an `end` closes one. The inline keyword form `do:` (a `do`
// immediately followed by `:`) is NOT a block opener — it is a one-line body — so we only
// count a `do` token that is a standalone word. We count word-bounded tokens so identifiers
// containing "do"/"end"/"fn" are not miscounted.
func elixirLineDelta(code string) int {
	delta := 0
	// Count `end` and `fn` from the word tokens.
	for _, tok := range tokenize(code) {
		switch tok {
		case "end":
			delta--
		case "fn":
			delta++
		}
	}
	// Count block-form `do` openers: a `do` that is a standalone word (surrounded by
	// non-identifier chars) and NOT the inline `do:` keyword. We scan for the `do` token and
	// check the following non-space char is not ':'.
	delta += elixirCountBlockDo(code)
	return delta
}

// elixirCountBlockDo counts standalone `do` block openers on a line, excluding the inline
// `do:` keyword form. A `do` qualifies when it is a whole word and the next non-space
// character after it is not ':' (which would make it the `do:` keyword).
func elixirCountBlockDo(code string) int {
	n := 0
	for i := 0; i+2 <= len(code); i++ {
		if code[i] != 'd' || code[i+1] != 'o' {
			continue
		}
		// Word boundary before.
		if i > 0 && isIdentByte(code[i-1]) {
			continue
		}
		// What follows the `do`?
		j := i + 2
		if j < len(code) && isIdentByte(code[j]) {
			continue // part of a longer identifier (e.g. "double")
		}
		// Skip spaces to find the next significant char.
		for j < len(code) && code[j] == ' ' {
			j++
		}
		if j < len(code) && code[j] == ':' {
			continue // the inline `do:` keyword form — not a block
		}
		n++
	}
	return n
}

// isIdentByte reports whether b is an identifier character (so we can test word boundaries).
func isIdentByte(b byte) bool {
	return b == '_' || (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9')
}

// nearestModule returns the name of the nearest enclosing `defmodule` block, or "" — the
// module a def belongs to (recorded as its Recv).
func nearestModule(syms []Symbol, stack []exBlock) string {
	for i := len(stack) - 1; i >= 0; i-- {
		if stack[i].isModule {
			return syms[stack[i].idx].Name
		}
	}
	return ""
}

// exLastSegment returns the final `.`-separated segment of a module alias (`MyApp.User` ->
// `User`).
func exLastSegment(name string) string {
	if i := strings.LastIndex(name, "."); i >= 0 {
		return name[i+1:]
	}
	return name
}

// stripElixirComment blanks string literals and a trailing `#` comment (length-preserving),
// so neither quoted text nor comment text reads as code. It does not span multi-line heredocs
// (`"""`) — an accepted approximation per the package note.
func stripElixirComment(s string) string {
	b := []rune(s)
	out := make([]rune, len(b))
	inStr := false
	var quote rune
	prevBackslash := false
	for i, r := range b {
		switch {
		case inStr:
			out[i] = ' '
			if r == quote && !prevBackslash {
				inStr = false
			}
		case r == '\'' || r == '"':
			inStr = true
			quote = r
			out[i] = ' '
		case r == '#':
			for j := i; j < len(b); j++ {
				out[j] = ' '
			}
			return string(out)
		default:
			out[i] = r
		}
		prevBackslash = r == '\\' && !prevBackslash
	}
	return string(out)
}

// elixirScanCalls extracts call references from one stripped line in the `name(` and
// `Module.func(` forms, dropping keyword matches and keeping the trailing simple name for
// dotted calls (Module.func() -> "func").
func elixirScanCalls(code, path string, lineNo int) []Reference {
	var out []Reference
	for _, m := range exCallRe.FindAllStringSubmatch(code, -1) {
		name := trailingName(m[1])
		if exKeyword[name] {
			continue
		}
		out = append(out, Reference{Name: name, Span: Span{File: path, StartLine: lineNo, EndLine: lineNo}})
	}
	return out
}
